# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

gem 'rspec'

gem 'byebug'

gem 'colorize'

# gem "rails"

# Added at 2018-02-23 08:12:00 -0800 by nate:
gem "pry", "~> 0.11.3"
